apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goapp
  name: goapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - image: shomaigu/zissyu:latest
        name: zissyu
        command: ["/bin/sh","-c"]
        args: ["go get && go run main.go"]
#        args: ["find / -name footer.html && pwd && ls"]

#        volumeMounts:
#        - name: my-volume
#          mountPath: /go/src/app
        ports:
          - containerPort: 1323

#      volumes:
#      - name: my-volume
#        hostPath:
#          path: /home/shoma/zi/zissyu/k8s/cmd/hello



---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mariadb
        name: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: "tmcit"
        - name: MARIADB_DATABASE
          value: "ques"
        - name: MARIADB_USER
          value: "docker"
        - name: MARIADB_PASSWORD
          value: "docker"
