apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goapp
  name: goapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - image: shomaigu/zissyu:latest
        name: zissyu
        command: ["/bin/sh","-c"]
        args: ["go get && go run main.go"]
      volumes:
      - name: my-volume
        hostPath:
          path: /cmd
