apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: goapp
  name: goapp
spec:
  ports:
  - port: 1323
    protocol: TCP
    targetPort: 1323
  selector:
    app: goapp
  type: NodePort
status:

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: db
  type: NodePort
status:
